# Generated by Django 6.0.1 on 2026-01-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_gameroom_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_output',
        ),
    ]
