# Generated by Django 6.0.1 on 2026-01-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_remove_task_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_output',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='initial_code',
            field=models.TextField(blank=True, default='# Входные данные: a, b\n# Сохраните результат в переменную result\n\nresult = a + b', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tests',
            field=models.JSONField(help_text='Формат: [{"variables": {"a": 1, "b": 2}, "expected": 3}]'),
        ),
    ]
