# Generated by Django 6.0.1 on 2026-01-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_task_expected_output_alter_task_initial_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_output',
        ),
    ]
